### ISSUE TITLE
Virus in minconda install ?

### ISSUE THREAD

**Issue by clsandt** [markotoplak/orange-infrared#110]
Hello marko
I tried to install the miniconda Orange at home but Avast told me it was infected by Win32:Evo-gen in Orange-Uninstal.exe

Bye

C

**Comment by markotoplak** [comment]
Do you still have the file you downloaded? Please send it to me somehow so we can take a look.

**Comment by clsandt** [comment]
I should still have it, I’ll send it from home.

C

De : Marko Toplak [mailto:notifications@github.com]
Envoyé : mercredi 15 novembre 2017 12:26
À : markotoplak/orange-infrared
Cc : SANDT Christophe; Author
Objet : Re: [markotoplak/orange-infrared] Virus in minconda install ? (#110)


Do you still have the file you downloaded? Please send it to me somehow so we can take a look.

**Comment by markotoplak** [comment]
Hi, please send me the file if you remember when you get home. :)

Best,
Marko

**Comment by clsandt** [comment]
https://www.dropbox.com/s/p4cb6o7n3zcb6ir/Orange3-3.7.0-Miniconda-x86_64.exe?dl=0https://www.dropbox.com/s/p4cb6o7n3zcb6ir/Orange3-3.7.0-Miniconda-x86_64.exe?dl=0

________________________________
De : Marko Toplak [notifications@github.com]
Envoyé : jeudi 16 novembre 2017 15:09
À : markotoplak/orange-infrared
Cc : SANDT Christophe; Author
Objet : Re: [markotoplak/orange-infrared] Virus in minconda install ? (#110)

Hi, please send me the file if you remember when you get home. :)

Best,
Marko

**Comment by markotoplak** [comment]
Your downloaded file is the same as we serve (it did not get corrupted in the transfer).

I tried scanning the offending file with multiple tools and it seems that your antivirus raised a false alarm.

![orange-uninstall](https://user-images.githubusercontent.com/552182/33430390-b4030342-d5d0-11e7-95e3-42e39b8400bb.png)

**Comment by clsandt** [comment]
OK
thanks.

C
________________________________
De : Marko Toplak [notifications@github.com]
Envoyé : jeudi 30 novembre 2017 13:16
À : markotoplak/orange-infrared
Cc : SANDT Christophe; Author
Objet : Re: [markotoplak/orange-infrared] Virus in minconda install ? (#110)


Closed #110<https://github.com/markotoplak/orange-infrared/issues/110>.
