### ISSUE TITLE
Tests for file readers for Agilent

### ISSUE THREAD

**Issue by markotoplak** [markotoplak/orange-infrared#121]
We need to add tests with  #117

**Comment by stuart-cls** [comment]
It's on my list, I'm trying to make the smallest possible test file :)
Thanks for merging #117

**Comment by markotoplak** [comment]
Do not try to break any records. Sufficiently small is small enough. :)

**Comment by stuart-cls** [comment]
Ah yes, but what is "sufficiently small"?

**Comment by markotoplak** [comment]
~100kB?
