### ISSUE TITLE
Upgrade path for #122 rename

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#126]
When I installed master with #122, I ended up with conflicting widget registrations in Orange. 
(Then I broke my pip rashly deleting references from site-packages ;) )

Is there anyway we can test upgrades when the package name changes?

**Comment by stuart-cls** [comment]
I tracked my specific problem down to a reference to my source directory in `Lib\site-packages\easy-install.pth` which I think was put there by running `python setup.py test`?

So this might not be a problem for normal users.

**Comment by stuart-cls** [comment]
Sorry for the extra noise but that wasn't it. The real problem was `Orange_Infrared.egg-info` directory hanging around in my source folder. Just in case some one else gets this error:

    ValueError: 'orangecontrib.infrared.widgets.owfft.OWFFT' already exists in the registry.

**Comment by markotoplak** [comment]
I tried installing new package (generated with python setup.py install) after the old version was installed. I get the same errors as you do.

But in my case the canvas still works. I get icon categories: "Spectroscopy" and "Infrared". Infrared is empty. I also get two entries in Add-ons dialog.

Also, to upgrade, users will have to install a "new" add-on: "Spectroscopy".

I think that these problems are not easily solvable, nor are show-stoppers. What do you think?

First removing Infrared and then installing Spectroscopy (or starting from a clean Orange install) works without strange artifacts.

**Comment by stuart-cls** [comment]
Yes, I think the fatal error was that the two packages were pointing to identical files on the drive. This is not the case for the normal upgrade.

I agree that while not ideal, having users uninstall `Infrared` and install `Spectroscopy` is not too onerous.

PS Merry Christmas!

**Comment by stuart-cls** [comment]
Yes, the widget already in registry ValueError above prevented the canvas from starting.
