### ISSUE TITLE
The big rename: users are still seeing "Infrared" in Add-ons

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#146]
and it's causing confusion.

Edit: The failure was unrelated.

**Comment by markotoplak** [comment]
What was the failure here

Since the last release (beginning of Jan) Infrared and Spectroscopy can actually be installed side by side. :)

I was planning to update Infrared with a transition package. I thought of making an empty package, that would just install the latest Spectroscopy version.

**Comment by stuart-cls** [comment]
It turned out it was an institutional permissions problem, they didn't have the right access to install the add-on in the old-style Windows Orange installer. I moved them to the miniconda version, which solved it.

**Comment by markotoplak** [comment]
We are also onto this one biolab/orange3#2883

**Comment by stuart-cls** [comment]
Ah okay! I thought it used to work but then I wondered if I was imagining things.

**Comment by markotoplak** [comment]
It already works. If you install Orange just for a single user, you can also install add-ons easily. But if you install Orange for all users, you need administrative permissions to install add-ons (run Orange as Administrator).

That PR would only put up a nice warning for it.
