### ISSUE TITLE
v0.3.2 is incompatible with Orange 3.9.0

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#152]
Hi Marko, 

@scott-cls just upgraded to Orange 3.9.0 and followed the new demo video and found that the Normalize preprocessor crashes.

I see you already fixed this in master with #140 but the build log for 0.3.2 shows it was already failing at that time on Orange master:

https://travis-ci.org/markotoplak/orange-infrared/jobs/325730345

Anyway could we do a small bugfix release? It's bad to have the new demo video crash so hard :D

**Comment by markotoplak** [comment]
Good catch. :D

Updated.

Thank you,
Marko
