### ISSUE TITLE
Integrate: Improve visual identification of regions

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#25]
@borondics says:

> On the graph, the labels overlap and they are unreadable.
> I think it would be better to color code the regions with a semi-transparent BG and the same color filled circle (or other) next to the Region name.

In addition, I would like to actually show the integration type in the preview. For example, a shaded-in area between the curve and the baseline used.

**Comment by markotoplak** [comment]
If we showed the shaded part we would only need 1 label per peak, where cluttering wouldn't be as problematic.

**Comment by markotoplak** [comment]
Integrate widget can now show multiple previews. They are also colored differently.

**Comment by borondics** [comment]
Hi,

Not sure what colors you mean? I have only the title bar of the individual
integrals showing colors, not the graph itself. Could we shade the area
under the graph?

[image: Inline image 1]

​Also, I have an important feature request. Would it be possible to have
the title bar of the individual integrals as a drop-down menu? This could
be useful to change the type of integration easily. At the moment you have
to add a new integral and set the limits every time.


f​

**Comment by markotoplak** [comment]
Ah, you need to select a curve (click on it). I'll change it to select one by default.

As to the feature request, I would not make it a priority. It is possible, of course, but the main difficulty to implementing it well would be that different kinds of integrals in principle require different parameters.

**Comment by borondics** [comment]
Ah! Looks very cool!! Yeah, selecting one curve will definitely help. :)

OK, no problem for the feature request.

There is another one though: could you take out the light yellow color from
the list? It is barely visible for anything other than the area integrals
and looks almost unnoticeable for the Closest Value and Peak Value.
