### ISSUE TITLE
Documenting requirements

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#3]
In #1 we introduced the scipy.signal.savgol_filter module, but this was only introduced in scipy version 0.14.0. Ubuntu 14.04 only has 0.13.3.

I can fix this with pip on my box but I'm wondering if we need to be documenting our requirements somewhere.

**Comment by markotoplak** [comment]
In setup.py there is a call of setup function with a parameter install_requires. It can be set to a list containing elements like this:

    'scipy',
    'six',
    'genesis-pyapi>=1.1.2',
    "slumber>=0.7.1",
    "requests>=2.6.0"

Generally, any requirement that can be installed with pip and does not conflict with Orange is OK. 

In practice there are often problems with installation on Mac and Windows, where most users do not have compilers. We will therefore need to distribute the correct scipy binary with either main Orange installation (that also requires scipy, but lower version is OK, in this case this option is preferable) or with the the add-on build.

**Comment by stuart-cls** [comment]
Okay, got it.
It looks like recent (3.2) versions of Orange install at least scipy 0.15.2 (on Windows) so we are okay so far.

**Comment by markotoplak** [comment]
Thanks, also on Mac it was OK. I added that requirement into the package.
