### ISSUE TITLE
OpusReader makes supported extensions dropdown too wide

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#36]
OPUS files can have extensions from *.0 to *.99 (or more, but the most I've seen so far is ~40) but @scott-cls observed that this makes the dropdown in a fileloader dialog (on Windows) extremely wide.

The way this is implemented by `EXTENSIONS` of `FileFormat` class is to specify each one. Is there a better way? Something like `*.#` ?

**Comment by markotoplak** [comment]
At the workshop in Trieste I also saw users having names like somethin.0004.

I opened a pull request in Orange that allows this: https://github.com/biolab/orange3/pull/2077

**Comment by markotoplak** [comment]
This is fixed on Orange git master and will be available for users in Orange 3.4.1.
