### ISSUE TITLE
Installation Issue opusFC

### ISSUE THREAD

**Issue by joesoap99** [markotoplak/orange-infrared#38]
Python 3.5 Anaconda 4,1,1 64 bit Windows 8,1, Orange 3.3

Was trying to install add-on and got following error message concerning opus FC.
Do I need to install an additional module? :

"Collecting Orange-Infrared
  Using cached Orange-Infrared-0.0.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Orange3 in c:\anaconda3\lib\site-packages (from Orange-Infrared)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.14.0 in c:\anaconda3\lib\site-packages (from Orange-Infrared)
Collecting spectral>=0.18 (from Orange-Infrared)
  Using cached spectral-0.18.zip
Collecting opusFC>=1.0.0b1 (from Orange-Infrared)
  Could not find a version that satisfies the requirement opusFC>=1.0.0b1 (from Orange-Infrared) (from versions: )
No matching distribution found for opusFC>=1.0.0b1 (from Orange-Infrared)"

**Comment by stuart-cls** [comment]
Hello,

There are currently no opusFC modules available for Python 3.5 on Windows. I just uploaded a 64-bit, Python 3.4 version to pypi if you would like to try that.

I was not aware there is a 3.5, 64-bit version of Orange on Windows, I've been targeting 3.4, 32-bit (the installer from the Orange website). How are you installing your version?

**Comment by joesoap99** [comment]
Thank you.
I will look into installing Python 3.4 alongside 3.5 if that will work.

The Orange 3.3,6  64 bit came ready packaged up in the Anaconda download. The basic program works fine.
The only problem I have had is with a couple of add-ons - this one and Spark. It seems Anaconda do not check for add-on compatibility.

**Comment by stuart-cls** [comment]
I have compiled and uploaded a Python 3.5 wheel for 64-bit Windows. I'll leave this open until I have completed the suite of platforms. Remaining is:

- [ ] Windows, 32-bit, Python 3.5
- [ ] MacOS, 64-bit, Python 3.5

**Comment by stuart-cls** [comment]
@markotoplak I believe this issue is now resolved.
