### ISSUE TITLE
Pretty up

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-infrared#45]
At some point we need to make our plots more pretty.
Some suggestions:
For the curves widget option "A" where we show the mean +- SD could we make the plot look something like this?
![image](https://cloud.githubusercontent.com/assets/6304794/19626867/10fbea2e-993b-11e6-8845-4602108d58e5.png)

The little help button is blocking the number on the axis. How about the layover type help like GMail has?

**Comment by markotoplak** [comment]
Done.
