### ISSUE TITLE
Feature constructor

### ISSUE THREAD

**Issue by clsandt** [markotoplak/orange-infrared#59]
Hi
I tried to use the Feature constructor to do a simple average of three values but I could not.
I don't even think the feature constructor is working on Windows Ornage 3.3.

Is it possible to write functions intuitively like: X1:=(Feature1 + Feature 2 + Feature 3)/3?

Greetings

Christophe

**Comment by markotoplak** [comment]
It should be possible. I've tested this on different data sets and discovered that this widget, as you found out, has problems with features whose names are numbers (this was your test case, right?). I will file a bug for this in main Orange.

Maybe there is something else.... What were your data like? Thanks, Marko

**Comment by clsandt** [comment]
My feature names were actually number. The widget transformed the names from xxxx.yyyy to xxxx_yyyy but was apparently unable to process them further.
My data were the same than the collagene set that we used for the training (except that I imported a new ASCII file from Unscrambler). I was trying to create a 'lipid concentration' continuous variable to use as a dependent variable for a regression. I selected 3 features directly from the File import widget with a Select column widget and imported them in the Feature constructor.

**Comment by markotoplak** [comment]
Thanks! I got the same symptoms. Will try to fix it now.

**Comment by stuart-cls** [comment]
Sounds like you're on it, but I also recently noticed that the feature constructor doesn't work on features named with numbers. In my case they were of the format 0000.00-0000.00 and were transformed to 0000_00_0000_00

**Comment by markotoplak** [comment]
This is merged into the main Orange branch and will be available with Orange 3.4.2, or, for adventurers, in the latest nightly builds at http://orange.biolab.si/download/files/nightly/
