### ISSUE TITLE
Curves: Unselected curves are almost invisible

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#65]
When viewing a spectrum in curves, the light gray is so faint I almost can't make it out on my monitor. It's even worse if you colour them (for example, collagen.csv, colour by type). This of course also makes the saved image unusable.

**Comment by markotoplak** [comment]
Thanks! Are they better now?

**Comment by stuart-cls** [comment]
Great! 

Also, I love the user of colorcet in owhyper, perceptually uniform colormaps by default!
