### ISSUE TITLE
"Files" does not display files

### ISSUE THREAD

**Issue by GioB81** [markotoplak/orange-infrared#74]
"files" widget on windows Anaconda 64bit ORANGE 3.4.2 Infrared package 0.17 does not display the folder content, no matter which file type is selected...

![image](https://cloud.githubusercontent.com/assets/19801152/26783708/e9910c1a-49f9-11e7-97c8-597509e1d724.png)

**Comment by markotoplak** [comment]
Could you try closing on opening Orange? This is known to happen when run for the first time (or after an update).

**Comment by GioB81** [comment]
did several times and also re-installed several times... if it were something that happened only the first time I used Orange I wouldn't had opened an issue... it just sees all the folders as empty, it sees only standard orange files (csv or tab or txt) not the others...

**Comment by markotoplak** [comment]
Can you please start Orange with

python -m Orange.canvas -l4 

and paste the console output?

**Comment by GioB81** [comment]
(C:\ProgramData\Anaconda3) C:\Users\giovanni.birarda>activate orange3

(orange3) C:\Users\giovanni.birarda>python-m Orange.canvas
'python-m' is not recognized as an internal or external command,
operable program or batch file.


or


C:\Users\giovanni.birarda>python-m Orange.canvas -I4
'python-m' is not recognized as an internal or external command,
operable program or batch file.


and here some errors:

(orange3) C:\Users\giovanni.birarda>orange-canvas
libpng warning: iCCP: known incorrect sRGB profile
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('
http://example.com/my-widget/docs/')'
C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py:993:
RuntimeWarning: Loaded module AnyQt._backport as a substitute for PyQt4
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py:993:
RuntimeWarning: Loaded module AnyQt._backport.QtCore as a substitute for
PyQt4.QtCore
  return pickle.loads(base64.decodebytes(string.encode('ascii')))
Could not load properties for 'File'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Distances'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Distance Map'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Data Table'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Scatter Plot'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Simple 2D Plotter'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Select Columns'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Select Rows'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'k-Means'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'EMSC'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves (3)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Scatter Plot (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves (2)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves (4)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Select Columns (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Preprocess (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Curves (5)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Data Table (2)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Distances (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
Could not load properties for 'Hierarchical Clustering (1)'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 699, in scheme_load
    properties = loads(data.data, data.format)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\scheme\readwrite.py",
line 993, in loads
    return pickle.loads(base64.decodebytes(string.encode('ascii')))
SystemError: unable to find to find module: PyQt4.QtCore
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

**Comment by markotoplak** [comment]
Please make a space between python and -m.

You can also use  orange-canvas -l4

**Comment by GioB81** [comment]
(orange3) C:\WINDOWS\system32>orange-canvas -l4
Starting 'Orange Canvas' application.
Starting CanvasApplicaiton with argv =
['C:\\ProgramData\\Anaconda3\\envs\\orange3\\Scripts\\orange-canvas-script.py'].
Adding search path 'orange' for prefix, 'canvas_icons'
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at
0x000001979BA46558>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache
('C:\\Users\\giovanni.birarda\\AppData\\Roaming\\Orange\\3.4.2\\Cache\\canvas\\registry-cache.pck').
Running widget discovery process.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\data\\contexthandlers.py'.
Could not import 'Orange.widgets.visualize.owparallelcoordinates'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\registry\discovery.py",
line 261, in iter_widget_descriptions
    module = asmodule(name)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\registry\discovery.py",
line 493, in asmodule
    return __import__(module, fromlist=[""])
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\visualize\owparallelcoordinates.py",
line 14, in <module>
    from Orange.widgets.visualize.owparallelgraph import OWParallelGraph
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\visualize\owparallelgraph.py",
line 17, in <module>
    from Orange.widgets.utils.plot import OWPlot, UserAxis, AxisStart,
AxisEnd, OWCurve, OWPoint, PolygonCurve, \
ImportError: cannot import name 'OWPlot'
Could not import 'Orange.widgets.visualize.owparallelgraph'.
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\registry\discovery.py",
line 261, in iter_widget_descriptions
    module = asmodule(name)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\canvas\registry\discovery.py",
line 493, in asmodule
    return __import__(module, fromlist=[""])
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\visualize\owparallelgraph.py",
line 17, in <module>
    from Orange.widgets.utils.plot import OWPlot, UserAxis, AxisStart,
AxisEnd, OWCurve, OWPoint, PolygonCurve, \
ImportError: cannot import name 'OWPlot'
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeviewer2d.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\visualize\\owviswidget.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagorastreeviewer.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthandlers.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
libpng warning: iCCP: known incorrect sRGB profile
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\orangecontrib\\infrared\\widgets\\gui.py'.
Ignoring
'C:\\ProgramData\\Anaconda3\\envs\\orange3\\lib\\site-packages\\orangecontrib\\infrared\\widgets\\line_geometry.py'.
Saving widget registry cache with 218 entries
('C:\\Users\\giovanni.birarda\\AppData\\Roaming\\Orange\\3.4.2\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at
0x00000197DBB4DA68> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider
for Orange3 3.4.2
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider
for Orange3-Datasets 0.1.4
An error occurred while fetching help inventory 'PyQt5.QtCore.QUrl('
http://example.com/my-widget/docs/')'

**Comment by markotoplak** [comment]
Thanks. Can you also do:

python -m unittest orangecontrib.infrared.tests.test_readers

**Comment by GioB81** [comment]
(orange3) C:\Users\giovanni.birarda>python -m unittest
orangecontrib.infrared.tests.test_readers
..C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\serverfiles\__init__.py:369:
ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  callback=callback)
.....
----------------------------------------------------------------------
Ran 7 tests in 4.720s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=356,
family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0,
laddr=('172.19.10.55', 57502), raddr=('193.2.72.57', 80)>

**Comment by markotoplak** [comment]
Hmmm, tests seem to be working.

I just installed the newest anaconda on windows 7 (64 bit), then installed Orange as instructed on the web page and then, within Orange, installed the add-on (through Options-Addons). I see also infrared files without any problems.

How did you install?

**Comment by markotoplak** [comment]
Could you replace your owfile.py in Orange distribution with this file: http://193.2.72.57/owfile.py

Here are my changes:
--- a/Orange/widgets/data/owfile.py
+++ b/Orange/widgets/data/owfile.py
@@ -105,7 +105,9 @@ class OWFile(widget.OWWidget, RecentPathsWComboMixin):
 
     variables = ContextSetting([])
 
-    dlg_formats = (
+    @property
+    def dlg_formats(self):
+        return (
         "All readable files ({});;".format(
             '*' + ' *'.join(FileFormat.readers.keys())) +
         ";;".join("{} (*{})".format(f.DESCRIPTION, ' *'.join(f.EXTENSIONS))

**Comment by GioB81** [comment]
I did it, now I see all but opus files...

**Comment by GioB81** [comment]
I did the same...

**Comment by markotoplak** [comment]
Great. This is progress. We suspect that there is a problem saving discovered widgets on your computer, but do not know why. We will fix the File widget in new release so that this problem will not appear again.

So you do not see "OPUS spectrum" in available file types list?

**Comment by GioB81** [comment]
I see them in the list but not in the selection window (so I cannot load
multiple files at once, for example)


gio

**Comment by markotoplak** [comment]
Could you make a screenshot, please?

**Comment by GioB81** [comment]
[image: Inline image 1]

**Comment by markotoplak** [comment]
Ok, I have been able to replicate this one. Matching filenames with wildcards seems not to work properly.

I will fix this later or tomorrow. Until then you can open orangecontrib/infrared/data.py on your computer and replace "fnmatch" with "fnmatchignore" in class OPUSReader.

**Comment by GioB81** [comment]
wait ...now it does this...

---------------------------- ValueError Exception
-----------------------------
Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\data\owfile.py",
line 324, in load_data
    self.apply_domain_edit()  # sends data
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\widgets\data\owfile.py",
line 413, in apply_domain_edit
    table = Table.from_numpy(domain, X, y, m, self.data.W)
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\data\table.py",
line 445, in from_numpy
    X, Y, W = _check_arrays(X, Y, W, dtype='float64')
  File
"C:\ProgramData\Anaconda3\envs\orange3\lib\site-packages\Orange\data\table.py",
line 1579, in _check_arrays
    % (len(array), shape_1))
ValueError: Leading dimension mismatch (0 != 2221)
-------------------------------------------------------------------------------

**Comment by markotoplak** [comment]
Ok, I think I fixed this. Just remove the addon (Options->Addons), restart Orange, install the addon again, restart Orange.

Please test.

**Comment by GioB81** [comment]
I am re-installing everything give me 5 mins... :)

**Comment by GioB81** [comment]
ok now I see everything
