### ISSUE TITLE
Standardize naming of Integrate() methods

### ISSUE THREAD

**Issue by stuart-cls** [markotoplak/orange-infrared#77]
Integral / peak height / cursor value methods have inconsistent naming throughout the add-on. 

Currently:

owintegrate:
 - Simple integral (y=0)
 - Integrate (baseline substracted[sic])
 - Peak Height
 - Baseline-Subtracted Peak
 - Closest Value

owhyper:
 - Integral from 0
 - Integral from baseline
 - Peak from 0
 - Peak from baseline
 - Value at

@scott-cls @markotoplak @borondics

**Comment by borondics** [comment]
Yeah, they should have the same names.

How about making icons too? I really like this feature in OPUS. Makes it super easy to understand what is going on, whereas the names can be misinterpreted.

**Comment by stuart-cls** [comment]
I think the owhyper names are overall more clear. Except I'm not sure if "Closest Value" or "Value at" is more accurate.

I agree about icons, it is #26
