### ISSUE TITLE
Curves widget: renaming

### ISSUE THREAD

**Issue by clsandt** [markotoplak/orange-infrared#81]
Would it be possible to rename the curve widget into Spectra or 'Plot Spectra'?

**Comment by markotoplak** [comment]
Of course. What do you think, @borondics ?

**Comment by borondics** [comment]
Sure, we could. Let's call it "Spectra", because the sister widget is "HyperSpectra" (could you actually capitalize that S in the name?

**Comment by markotoplak** [comment]
Done.
